language: node_js
node_js:
    - "6"
branches:
    only:
    - master
    - develop
before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
before_deploy:
    - if [ "$TRAVIS_BRANCH" = "develop" ]; then
        echo -e "\e[1m\e[36mBuilding for develop";
        export TARGET_BUCKET="bdev.c4gnv.com";
        export TARGET_REGION="us-east-1";
      fi
    - if [ "$TRAVIS_BRANCH" = "master" ]; then
        echo -e "\e[1m\e[36mBuilding for production";
        export TARGET_BUCKET="business.cityofgainesville.org";
        export TARGET_REGION="us-east-2";
      fi
    - aws s3 rm s3://${TARGET_BUCKET}/ --recursive --region $TARGET_REGION
install:
    - yarn install --no-progress
script: yarn run build

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # Declared in travis build settings
    secret_access_key: $AWS_SECRET_KEY # Declared in travis build settings
    bucket: $TARGET_BUCKET
    cache_control: "max-age=604800"
    skip_cleanup: true
    region: $TARGET_REGION
    local_dir: build
    detect_encoding: true
    on:
        branch:
        - master
        - develop
notifications:
    email:
        on_failure: always
